name: Bootcamp2020Sample

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Installing Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12  
        
    - name: Installing Surge
      run: npm install --global surge
    - name: Deploy using surge
      run: surge ./ http://bootcamp2020-anasshad.surge.sh --token $ {{ secrets.SURGE_TOKEN }}
